
server {
    listen 1025;
    server_name localhost;
    root HTTP/DefaultPages;
    index index.html index.htm;
    autoindex off;
    allow_methods GET POST DELETE;
    client_max_body_size 1m;
    error_page 404 /errors/404.html;

    
    location / {
        index index.html index.htm;
        allow_methods GET POST DELETE;
    }

    
    location /css {
        allow_methods GET;
    }

    location /js {
        allow_methods GET;
    }

    location /image {
        allow_methods GET;
    }

    
    
    location /Hello {
        root HTTP/DefaultPages/rootMappedPath;
        index index.html index.htm;
        allow_methods GET;
    }

    
    
    location /Pages {
        autoindex on;
        allow_methods GET;
    }

    
    
    
    location /autoindex-off {
        autoindex off;
        allow_methods GET;
    }

    
    
    location /old-page {
        return 301 /new-location;
    }

    
    location /temp-page {
        return 302 /other-location;
    }

    
    
    
    location /get-only {
        index index.html index.htm;
        allow_methods GET;
    }

    location /upload {
        allow_methods GET POST DELETE;
        client_body_in_file_only on;
        delete_files on;
    }

    location /upload-limit {
        allow_methods GET POST DELETE;
        client_max_body_size 64b;
        client_body_in_file_only on;
        delete_files on;
    }

    location /secret {
        allow_methods GET;
    }

    
    
    location /ping {
        index index.html index.htm;
        allow_methods GET;
    }


    
    location /cgi-bin {
        allow_methods GET POST;
        cgi_pass .py /usr/bin/python3;
    }
}


server {
    listen 1025;
    server_name site2.local;
    root HTTP/DefaultPages/site2;
    index index.html;
    allow_methods GET;

    location / {
        index index.html;
        allow_methods GET;
    }
}



server {
    listen 1026;
    server_name localhost;
    root HTTP/DefaultPages;
    index index.html index.htm;
    allow_methods GET POST DELETE;

    location / {
        index index.html index.htm;
        allow_methods GET;
    }
}


types {
    text/html                        html htm shtml;
    text/css                         css;
    text/plain                       txt;
    image/jpeg                       jpeg jpg;
    image/png                        png;
    image/gif                        gif;
    application/javascript           js;
    application/octet-stream         bin exe dll;
    application/json                 json;
    application/x-www-form-urlencoded form;
}