server {
    listen 1025;
	server_name localhost;
	root HTTP/DefaultPages/Pages;
	index index.html index.htm;
	autoindex off;
	allow_methods GET POST DELETE;
	client_max_body_size 1m;
	error_page 404 /errors/404.html;

	location / {
		root HTTP/DefaultPages/scripts;
		cgi_pass .cs /usr/bin/dotnet;
	}

	location /google {
		return 301 https://www.google.com;
	}
	location / {
		index index.html index.htm;
		allow_methods GET POST DELETE;
	}

	location /css {
	}
	location /js {
	}
	location /image {
	}

	location /Hello {
		root HTTP/DefaultPages/rootMappedPath;
		index index.html index.htm;
	}
    location /scripts {
        root HTTP/DefaultPages/;
        cgi_pass .py /usr/bin/python3;
    }

	location /Pages {
		autoindex on;
		
	}

	location /autoindex-off {
		autoindex off;
	}

	location /old-page {
		return 301 /new-location;
	}
	location /temp-page {
		return 302 /other-location;
	}

	location /get-only {
		index index.html index.htm;
		allow_methods GET;
	}

	location /upload {
		client_body_in_file_only on;
		delete_files on;
	}

	location /upload-limit {
		client_max_body_size 64b;
		client_body_in_file_only on;
		delete_files on;
	}

	location /secret {
	}

	location / {
		cgi_pass .py /usr/bin/python3;
	}
}

server {
	listen 1026;
	server_name localhost;
	root HTTP/DefaultPages;
	index index.html index.htm;
	allow_methods GET POST DELETE;

	location / {
		index index.html index.htm;
	}
}

types {
	text/html       html htm shtml;
	text/css        css;
	text/plain      txt;
	image/jpeg      jpeg jpg;
	image/png       png;
	image/gif       gif;
	application/javascript   js;
	application/octet-stream bin exe dll;
}
