server {
    listen 1025;
	listen 1026;
	server_name localhost;
	root EngineX/www;
	index index.htm;
	autoindex on;
	client_max_body_size 1k;
	cgi_timeout 3;
	keep_alive_timeout 300;
	client_read_timeout 300;

}


types {
	text/html       html htm shtml;
	text/css        css;
	text/plain      txt;
	image/jpeg      jpeg jpg;
	image/png       png;
	image/gif       gif;
	application/javascript   js;
	application/octet-stream bin exe dll;
}
