server {
	listen 1025;
	server_name localhost;
}

types {
	text/html       html htm shtml;
	text/css        css;
	text/plain      txt;
	image/jpeg      jpeg jpg;
	image/png       png;
	image/gif       gif;
	application/javascript   js;
	application/octet-stream bin exe dll;
}
