server {
    allow_methods GET;
	root EngineX/www-subject-tester;
	index index.htm;
	autoindex on;
	cgi_timeout 60;
	keep_alive_timeout 4;
	client_read_timeout 4;

	
    location /directory/Yeah {
		root EngineX/;
	}

	location /directory/Yeah/not_happy.bad_extension {
		root EngineX/www-subject-tester;
	}

	location /post_body {
		client_body_in_file_only on;
		client_max_body_size 100b;
		allow_methods POST;
	}

	location /directory/ {
		index youpi.bad_extension;
		allow_methods GET;
	}

	location /directory/ {
		allow_methods POST;
		cgi_pass .bla EngineX/www-subject-tester/cgi_tester;
	}
}

types {
	text/html  html htm;
}